main: com.quackings.spigot.testplugin.App
name: TestPlugin
version: 0.1
author: Kyle Rush
website: https://quackings.com

commands:
  bruhwhy:
    description: testing command
    permission: testplugin.bruhwhy
    usage: /<command>

permissions: {}