main: com.quackings.spigot.testplugin.App
name: TestPlugin
version: 0.1
author: Kyle Rush
website: https://quackings.com

commands:
  args:
    description: args test
    permission: testplugin.args
    usage: /<command>
  
  disable:
    description: Disables the plugin
    permission: testplugin.disable
    ussage: /<command>
  
  # menu:
  #   description: Menu
  #   permission: testplugin.menu
  #   ussage: /<command>

permissions: {}